export type Colors = {
  colorTextInputDisabled: string;
  colorTextInput: string;
  backgroundInputDisabled: string;
  backgroundInput: string;
  background: string;
  colorIconPrimary: string;
  colorIconSecondary: string;
  colorIconInfo: string;
  colorIconSuccess: string;
  colorIconWarning: string;
  colorIconCritical: string;
  colorInfoCheckBoxRadio: string;
  colorFormLabel: string;
  colorIconCheckboxRadio: string;
  colorIconCheckboxRadioDisabled: string;
  colorPlaceholderInput: string;
  colorTextLoading: string;
  backgroundButtonPrimary: string;
  backgroundButtonSecondary: string;
  backgroundButtonInfo: string;
  backgroundButtonSuccess: string;
  backgroundButtonWarning: string;
  backgroundButtonCritical: string;
  backgroundButtonPrimaryHover: string;
  backgroundButtonSecondaryHover: string;
  backgroundButtonInfoHover: string;
  backgroundButtonSuccessHover: string;
  backgroundButtonWarningHover: string;
  backgroundButtonCriticalHover: string;
  backgroundButtonPrimaryActive: string;
  backgroundButtonSecondaryActive: string;
  backgroundButtonInfoActive: string;
  backgroundButtonSuccessActive: string;
  backgroundButtonWarningActive: string;
  backgroundButtonCriticalActive: string;
  colorTextButtonPrimaryBordered: string;
  colorTextButtonPrimaryBorderedHover: string;
  colorTextButtonPrimaryBorderedActive: string;
  colorTextButtonSecondaryBordered: string;
  colorTextButtonSecondaryBorderedHover: string;
  colorTextButtonSecondaryBorderedActive: string;
  colorTextButtonInfoBordered: string;
  colorTextButtonInfoBorderedHover: string;
  colorTextButtonInfoBorderedActive: string;
  colorTextButtonSuccessBordered: string;
  colorTextButtonSuccessBorderedHover: string;
  colorTextButtonSuccessBorderedActive: string;
  colorTextButtonWarningBordered: string;
  colorTextButtonWarningBorderedHover: string;
  colorTextButtonWarningBorderedActive: string;
  colorTextButtonCriticalBordered: string;
  colorTextButtonCriticalBorderedHover: string;
  colorTextButtonCriticalBorderedActive: string;
  backgroundButtonBordered: string;
  backgroundButtonBorderedHover: string;
  backgroundButtonBorderedActive: string;
  colorTextButtonPrimary: string;
  colorTextButtonPrimaryHover: string;
  colorTextButtonPrimaryActive: string;
  colorTextButtonSecondary: string;
  colorTextButtonSecondaryHover: string;
  colorTextButtonSecondaryActive: string;
  colorTextButtonInfo: string;
  colorTextButtonInfoHover: string;
  colorTextButtonInfoActive: string;
  colorTextButtonSuccess: string;
  colorTextButtonSuccessHover: string;
  colorTextButtonSuccessActive: string;
  colorTextButtonWarning: string;
  colorTextButtonWarningHover: string;
  colorTextButtonWarningActive: string;
  colorTextButtonCritical: string;
  colorTextButtonCriticalHover: string;
  colorTextButtonCriticalActive: string;
  borderColorButtonPrimaryBordered: string;
  borderColorButtonPrimaryBorderedActive: string;
  borderColorButtonPrimaryBorderedHover: string;
  borderColorButtonSecondaryBordered: string;
  borderColorButtonSecondaryBorderedActive: string;
  borderColorButtonSecondaryBorderedHover: string;
  borderColorButtonInfoBordered: string;
  borderColorButtonInfoBorderedActive: string;
  borderColorButtonInfoBorderedHover: string;
  borderColorButtonSuccessBordered: string;
  borderColorButtonSuccessBorderedActive: string;
  borderColorButtonSuccessBorderedHover: string;
  borderColorButtonWarningBordered: string;
  borderColorButtonWarningBorderedActive: string;
  borderColorButtonWarningBorderedHover: string;
  borderColorButtonCriticalBordered: string;
  borderColorButtonCriticalBorderedActive: string;
  borderColorButtonCriticalBorderedHover: string;
  colorHeading: string;
  backgroundSeparator: string;
};

const color = {
  colorTextInputDisabled: '#BAC7D5',
  colorTextInput: '#252A31',
  backgroundInputDisabled: '#EFF2F5',
  backgroundInput: '#FFFFFF',
  background: 'white',
  colorIconPrimary: '#252A31',
  colorIconSecondary: '#5F738C',
  colorIconInfo: '#0172CB',
  colorIconSuccess: '#28A138',
  colorIconWarning: '#E98305',
  colorIconCritical: '#D21C1C',
  colorInfoCheckBoxRadio: '#5F738C',
  colorFormLabel: '#252A31',
  colorIconCheckboxRadio: '#00A991',
  colorIconCheckboxRadioDisabled: '#BAC7D5',
  colorPlaceholderInput: '#BAC7D5',
  colorTextLoading: '#BAC7D5',
  backgroundButtonPrimary: '#00A991',
  backgroundButtonSecondary: '#E8EDF1',
  backgroundButtonInfo: '#0172CB',
  backgroundButtonSuccess: '#28A138',
  backgroundButtonWarning: '#E98305',
  backgroundButtonCritical: '#D21C1C',
  backgroundButtonPrimaryHover: '#009882',
  backgroundButtonSecondaryHover: '#DCE3E9',
  backgroundButtonInfoHover: '#0161AC',
  backgroundButtonSuccessHover: '#238B31',
  backgroundButtonWarningHover: '#DC7C05',
  backgroundButtonCriticalHover: '#B91919',
  backgroundButtonPrimaryActive: '#008F7B',
  backgroundButtonSecondaryActive: '#CAD4DE',
  backgroundButtonInfoActive: '#01508E',
  backgroundButtonSuccessActive: '#1D7228',
  backgroundButtonWarningActive: '#CD7304',
  backgroundButtonCriticalActive: '#9D1515',
  colorTextButtonPrimaryBordered: '#00A991',
  colorTextButtonPrimaryBorderedHover: '#009882',
  colorTextButtonPrimaryBorderedActive: '#008F7B',
  colorTextButtonSecondaryBordered: '#252A31',
  colorTextButtonSecondaryBorderedHover: '#181B20',
  colorTextButtonSecondaryBorderedActive: '#0B0C0F',
  colorTextButtonInfoBordered: '#0172CB',
  colorTextButtonInfoBorderedHover: '#0161AC',
  colorTextButtonInfoBorderedActive: '#01508E',
  colorTextButtonSuccessBordered: '#28A138',
  colorTextButtonSuccessBorderedHover: '#238B31',
  colorTextButtonSuccessBorderedActive: '#1D7228',
  colorTextButtonWarningBordered: '#E98305',
  colorTextButtonWarningBorderedHover: '#DC7C05',
  colorTextButtonWarningBorderedActive: '#CD7304',
  colorTextButtonCriticalBordered: '#D21C1C',
  colorTextButtonCriticalBorderedHover: '#B91919',
  colorTextButtonCriticalBorderedActive: '#9D1515',
  backgroundButtonBordered: 'transparent',
  backgroundButtonBorderedHover: '#F5F7F9',
  backgroundButtonBorderedActive: '#F5F7F9',
  colorTextButtonPrimary: '#FFFFFF',
  colorTextButtonPrimaryHover: '#FFFFFF',
  colorTextButtonPrimaryActive: '#FFFFFF',
  colorTextButtonSecondary: '#252A31',
  colorTextButtonSecondaryHover: '#181B20',
  colorTextButtonSecondaryActive: '#0B0C0F',
  colorTextButtonInfo: '#FFFFFF',
  colorTextButtonInfoHover: '#FFFFFF',
  colorTextButtonInfoActive: '#FFFFFF',
  colorTextButtonSuccess: '#FFFFFF',
  colorTextButtonSuccessHover: '#FFFFFF',
  colorTextButtonSuccessActive: '#FFFFFF',
  colorTextButtonWarning: '#FFFFFF',
  colorTextButtonWarningHover: '#FFFFFF',
  colorTextButtonWarningActive: '#FFFFFF',
  colorTextButtonCritical: '#FFFFFF',
  colorTextButtonCriticalHover: '#FFFFFF',
  colorTextButtonCriticalActive: '#FFFFFF',
  borderColorButtonPrimaryBordered: '#00A991',
  borderColorButtonPrimaryBorderedActive: '#008F7B',
  borderColorButtonPrimaryBorderedHover: '#009882',
  borderColorButtonSecondaryBordered: '#252A31',
  borderColorButtonSecondaryBorderedHover: '#181B20',
  borderColorButtonSecondaryBorderedActive: '#0B0C0F',
  borderColorButtonInfoBordered: '#0172CB',
  borderColorButtonInfoBorderedHover: '#0161AC',
  borderColorButtonInfoBorderedActive: '#01508E',
  borderColorButtonSuccessBordered: '#28A138',
  borderColorButtonSuccessBorderedHover: '#238B31',
  borderColorButtonSuccessBorderedActive: '#1D7228',
  borderColorButtonWarningBordered: '#E98305',
  borderColorButtonWarningBorderedHover: '#DC7C05',
  borderColorButtonWarningBorderedActive: '#CD7304',
  borderColorButtonCriticalBordered: '#D21C1C',
  borderColorButtonCriticalBorderedHover: '#B91919',
  borderColorButtonCriticalBorderedActive: '#9D1515',
  colorHeading: '#252A31',
  backgroundSeparator: '#EFF2F5',
};

export default color;
